c:\utils\bin2obj32 gif_grid.gif gif_grid.obj _gif_grid

c:\utils\bin2obj32 gif_onesph.gif gif_onesph.obj _gif_onesph

c:\utils\bin2obj32 gif_hippy1.gif gif_hippy1.obj _gif_hippy1

c:\utils\bin2obj32 gif_hippy2.gif gif_hippy2.obj _gif_hippy2

c:\utils\bin2obj32 gif_font.gif gif_font.obj _gif_font

c:\utils\bin2obj32 gif_face1.gif gif_face1.obj _gif_face1

c:\utils\bin2obj32 gif_face2.gif gif_face2.obj _gif_face2

c:\utils\bin2obj32 gif_face3.gif gif_face3.obj _gif_face3
c:\utils\bin2obj32 gif_face4.gif gif_face4.obj _gif_face4

c:\utils\bin2obj32 gif_fullscreen.gif gif_fullscreen.obj _gif_fullscreen

c:\utils\bin2obj32 gif_big.gif gif_big.obj _gif_big
c:\utils\bin2obj32 gif_hands.gif gif_hands.obj _gif_hands

c:\utils\bin2obj32 gif_pixlad.gif gif_pixlad.obj _gif_pixlad

c:\utils\bin2obj32 vobbel4.mod intromusic.obj _intromusic