c:\utils\bin2obj32 gif_psikorp.gif gif_psikorp.obj _gif_psikorp

c:\utils\bin2obj32 gif_psikorp2.gif gif_psikorp2.obj _gif_psikorp2
c:\utils\bin2obj32 gif_flare.gif gif_flare.obj _gif_flare

c:\utils\bin2obj32 gif_flower.gif gif_flower.obj _gif_flower
c:\utils\bin2obj32 gif_greetback.gif gif_greetback.obj _gif_greetback
c:\utils\bin2obj32 gif_grid.gif gif_grid.obj _gif_grid
c:\utils\bin2obj32 gif_psiband.gif gif_psiband.obj _gif_psiband
c:\utils\bin2obj32 gif_rost.gif gif_rost.obj _gif_rost

c:\utils\bin2obj32 gif_landscape.gif gif_landscape.obj _gif_landscape
c:\utils\bin2obj32 gif_clouds.gif gif_clouds.obj _gif_clouds
c:\utils\bin2obj32 gif_title.gif gif_title.obj _gif_title

c:\utils\bin2obj32 gif_psikorp3.gif gif_psikorp3.obj _gif_psikorp3

c:\utils\bin2obj32 gif_full.gif gif_full.obj _gif_full

c:\utils\bin2obj32 gif_font.gif gif_font.obj _gif_font

c:\utils\bin2obj32 gif_twister.gif gif_twister.obj _gif_twister
c:\utils\bin2obj32 gif_twister2.gif gif_twister2.obj _gif_twister2
c:\utils\bin2obj32 gif_symboler.gif gif_symboler.obj _gif_symboler

c:\utils\bin2obj32 gif_faces.gif gif_faces.obj _gif_faces
c:\utils\bin2obj32 gif_green.gif gif_green.obj _gif_green
c:\utils\bin2obj32 gif_names.gif gif_names.obj _gif_names

c:\utils\bin2obj32 glass.xm intromusic.obj _intromusic

c:\utils\bin2obj32 gif_krom.gif gif_krom.obj _gif_krom
c:\utils\bin2obj32 gif_silu.gif gif_silu.obj _gif_silu

c:\utils\bin2obj32 gif_psikorp4.gif gif_psikorp4.obj _gif_psikorp4
